src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Titre;

    /**
     * @ORM\Column(type="text")
     */
    private $Contenu;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Categorie;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Image;

    /**
     * @ORM\Column(type="date")
     */
    private $DateCreation;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $DateModification;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Autheur;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->Contenu;
    }

    public function setContenu(string $Contenu): self
    {
        $this->Contenu = $Contenu;

        return $this;
    }

    public function getCategorie(): ?string
    {
        return $this->Categorie;
    }

    public function setCategorie(?string $Categorie): self
    {
        $this->Categorie = $Categorie;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(?string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->DateCreation;
    }

    public function setDateCreation(\DateTimeInterface $DateCreation): self
    {
        $this->DateCreation = $DateCreation;

        return $this;
    }

    public function getDateModification(): ?\DateTimeInterface
    {
        return $this->DateModification;
    }

    public function setDateModification(?\DateTimeInterface $DateModification): self
    {
        $this->DateModification = $DateModification;

        return $this;
    }

    public function getAutheur(): ?string
    {
        return $this->Autheur;
    }

    public function setAutheur(string $Autheur): self
    {
        $this->Autheur = $Autheur;

        return $this;
    }
}

src/Controller/BlogController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Article;
use App\Repository\ArticleRepository;

class BlogController extends AbstractController
{
    /**
     * @Route("/blog", name="blog")
     */
    public function index(ArticleRepository $repo)
    {
      
        $articles = $repo->findAll();
        $reverse = array_reverse($articles);
        dump($articles);
        

        return $this->render('blog/index.html.twig', [
            'controller_name' => 'BlogController',
            'articles' => $reverse,
        ]);
    }

    /**
     * @Route("/blog/{id}", name="blog_show")
     */
    public function show(Article $article)
    {
        return $this->render('blog/show.html.twig', [
            'controller_name' => 'BlogController',
            'article' => $article,
        ]);
    }

}

templates/Blog/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BlogController!{% endblock %}

{% block stylesheets %}
{% endblock %}

{% block body %}


    <div class="row">

      <!-- Blog Entries Column -->
      <div class="col-md-8">

        <h1 class="my-4">Page Heading
          <small>Secondary Text</small>
        </h1>

        <!-- Blog Post -->
      {% for article in articles %}
        <article>
          <h2>{{ article.titre }}</h2>
          <div class="metadata">Ecrit le {{ article.dateCreation | date('d/m/Y')}}  dans la catégorie {{ article.categorie}}</div>
          <div class="content">
            {% set some_html = article.contenu %}     
            <img src="{{ article.image}}" alt="{{ article.titre }}">
            <p>
              {{ some_html[:300]|striptags ~ ' ...' }}  
            </p>
            <a href="{{ path('blog_show', {'id' : article.id }) }}" class="btn btn-primary">Lire la suite</a>
          </div>
        </article>
        <br>
        <hr>
      {% endfor %}


        <!-- Pagination -->
        {# <ul class="pagination justify-content-center mb-4">
          <li class="page-item">
            <a class="page-link" href="#">&larr; Older</a>
          </li>
          <li class="page-item disabled">
            <a class="page-link" href="#">Newer &rarr;</a>
          </li>
        </ul> #}

      </div>
{# 
      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Search Widget -->
        <div class="card my-4">
          <h5 class="card-header">Search</h5>
          <div class="card-body">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-btn">
                <button class="btn btn-secondary" type="button">Go!</button>
              </span>
            </div>
          </div>
        </div>

        <!-- Categories Widget -->
        <div class="card my-4">
          <h5 class="card-header">Categories</h5>
          <div class="card-body">
            <div class="row">
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">Web Design</a>
                  </li>
                  <li>
                    <a href="#">HTML</a>
                  </li>
                  <li>
                    <a href="#">Freebies</a>
                  </li>
                </ul>
              </div>
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">JavaScript</a>
                  </li>
                  <li>
                    <a href="#">CSS</a>
                  </li>
                  <li>
                    <a href="#">Tutorials</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>

        <!-- Side Widget -->
        <div class="card my-4">
          <h5 class="card-header">Side Widget</h5>
          <div class="card-body">
            You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
          </div>
        </div>

      </div> #}

    </div>
    <!-- /.row -->

  <script type="text/javascript">
  var count = 6;
  var redirect = "http://127.0.0.1:8000/blog";
  
  function countDown(){
      var timer = document.getElementById("timer");
      if(count > 0){
          count--;
          timer.innerHTML = "This page will redirect in "+count+" seconds.";
          setTimeout("countDown()", 1000);
      }else{
          window.location.href = redirect;
      }
  }
  </script>
  
  Our webpage has beed moved. Please update your bookmarks for the new site.
  <br>
  
  <span id="timer">
  <script type="text/javascript">countDown();</script>
  </span>
{% endblock %}

templates/Blog/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello TemplateController!{% endblock %}

{% block body %}
        <article>
          <h2>{{ article.titre }}</h2>
          <div class="metadata">Ecrit le {{ article.dateCreation | date('d/m/Y')}}  dans la catégorie {{ article.categorie}}</div>
          <div class="content">  
            <img src="{{ article.image}}" alt="{{ article.titre }}">
            <p>
              {{ article.contenu }}  
            </p>
          </div>
        </article>
{% endblock %}